(function () {
  "use strict";
  const state = { token: "", code: "", review: null };
  const $ = (selector) => document.querySelector(selector);
  const labels = { display_name: "Aday", rank: "Yeterlilik / rütbe", sea_service_summary: "Deniz hizmeti özeti", vessel_experience: "Gemi tecrübesi", certificate_status: "Sertifika durumu", interview_result: "Görüşme sonucu", company_notes: "Şirket notları" };
  function apiBase() { return /^(localhost|127\.0\.0\.1)$/i.test(location.hostname) ? "http://localhost:3000" : String(window.Allona?.config?.apiBaseUrl || "https://api.allonahub.com").replace(/\/$/, ""); }
  async function post(path, body) { const response = await fetch(`${apiBase()}${path}`, { method: "POST", headers: { Accept: "application/json", "Content-Type": "application/json" }, body: JSON.stringify(body) }); const payload = await response.json().catch(() => ({})); if (!response.ok || payload.ok === false) throw new Error(payload.message || "İşlem tamamlanamadı."); return payload; }
  function status(message, ok) { const target = $("[data-review-status]"); target.textContent = message || ""; target.style.color = ok ? "#087a5b" : "#9a1a2f"; }
  function printable(value) { if (Array.isArray(value)) return value.map((item) => typeof item === "object" ? Object.values(item).filter(Boolean).join(" · ") : String(item)).join("\n") || "-"; if (value && typeof value === "object") return Object.values(value).filter(Boolean).join(" · ") || "-"; return String(value || "-"); }
  $("[data-review-access-form]").addEventListener("submit", async (event) => { event.preventDefault(); const form = new FormData(event.target); state.token = String(form.get("token") || ""); state.code = String(form.get("code") || ""); const button = event.target.querySelector("button"); button.disabled = true; try { const payload = await post("/v1/maritime/reviewer-pass/access", { token: state.token, code: state.code }); state.review = payload.review; $("[data-review-login]").hidden = true; $("[data-review-content]").hidden = false; $("[data-review-title]").textContent = payload.review.job?.job_title || "Aday İncelemesi"; $("[data-review-purpose]").textContent = payload.review.purpose; const fields = $("[data-review-fields]"); fields.replaceChildren(...Object.entries(payload.review.candidate || {}).map(([key, value]) => { const row = document.createElement("div"); const dt = document.createElement("dt"); const dd = document.createElement("dd"); dt.textContent = labels[key] || key; dd.textContent = printable(value); row.append(dt, dd); return row; })); if(payload.review.download_allowed){const download=document.createElement("button");download.type="button";download.dataset.reviewDownload="true";download.textContent="Yetkili Özeti İndir";fields.after(download);} status("Erişim doğrulandı.", true); } catch (error) { status(error.message); } finally { button.disabled = false; } });
  $("[data-review-decision-form]").addEventListener("submit", async (event) => { event.preventDefault(); const form = new FormData(event.target); const button = event.target.querySelector("button"); button.disabled = true; try { await post("/v1/maritime/reviewer-pass/decision", { token: state.token, code: state.code, decision: form.get("decision"), comment: String(form.get("comment") || "") }); event.target.replaceChildren(Object.assign(document.createElement("p"), { textContent: "Kararınız güvenli biçimde kaydedildi." })); status("İnceleme tamamlandı.", true); } catch (error) { status(error.message); button.disabled = false; } });
  document.addEventListener("click",async(event)=>{const button=event.target.closest("[data-review-download]");if(!button)return;button.disabled=true;try{const response=await fetch(`${apiBase()}/v1/maritime/reviewer-pass/export`,{method:"POST",headers:{Accept:"application/json","Content-Type":"application/json"},body:JSON.stringify({token:state.token,code:state.code})});if(!response.ok){const payload=await response.json().catch(()=>({}));throw new Error(payload.message||"İndirme tamamlanamadı.");}const blob=await response.blob();const url=URL.createObjectURL(blob);const link=document.createElement("a");link.href=url;link.download=`AllonaHub_Maritime_Review_${state.review?.pass_id?.slice(0,8)||"secure"}.json`;link.click();URL.revokeObjectURL(url);status("Yetkili özet indirildi.",true);}catch(error){status(error.message);}finally{button.disabled=false;}});
})();
